version: '3.9'

services:
    app:
        env_file: .env
        image: marcelkonrad/fuschpool
        labels:
            - "traefik.enable=true"
            - "traefik.backend=fuschpool"
            - "traefik.frontend.rule=Host:fuschpool.koma84.de"
            - "traefik.docker.network=web"
        networks:
            - mysql
            - web
        ports:
            - "80:8000"
        restart: "unless-stopped"
    huey:
        command: /app/manage.py run_huey
        image: marcelkonrad/fuschpool
        labels:
            - "traefik.enable=false"
        networks:
            - mysql
        restart: "unless-stopped"
    redis:
        image: redis:alpine
        labels:
            - "traefik.enable=false"
        networks:
            - mysql
        restart: "unless-stopped"

networks:
    web:
        external: true
    mysql:
        external: true
