[tool.poetry]
name = "fuschpool"
version = "0.1.0"
description = "Pick'em pool for family and friends"
authors = ["Marcel Konrad <makonrad@gmx.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
django = "~3.0.3"
psycopg2 = "^2.8.4"
django-bootstrap4 = "^1.1.1"
Authlib = "^0.13"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
pyyaml = "^5.3"
pytest-django = "^3.8.0"
pytest = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
