# Generated by Django 3.2.10 on 2021-12-29 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_id', models.PositiveIntegerField()),
                ('home_team_score', models.PositiveSmallIntegerField(default=None, null=True)),
                ('visitor_team_score', models.PositiveSmallIntegerField(default=None, null=True)),
                ('final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Atlanta Falcons'), (2, 'Buffalo Bills'), (3, 'Chicago Bears'), (4, 'Cincinnati Bengals'), (5, 'Cleveland Browns'), (6, 'Dallas Cowboys'), (7, 'Denver Broncos'), (8, 'Detroit Lions'), (9, 'Green Bay Packers'), (10, 'Tennessee Titans'), (11, 'Indianapolis Colts'), (12, 'Kansas City Chiefs'), (13, 'Las Vegas Raiders'), (14, 'Los Angeles Rams'), (15, 'Miami Dolphins'), (16, 'Minnesota Vikings'), (17, 'New England Patriots'), (18, 'New Orleans Saints'), (19, 'New York Giants'), (20, 'New York Jets'), (21, 'Philadelphia Eagles'), (22, 'Arizona Cardinals'), (23, 'Pittsburgh Steelers'), (24, 'Los Angeles Chargers'), (25, 'San Francisco 49ers'), (26, 'Seattle Seahawks'), (27, 'Tampa Bay Buccaneers'), (28, 'Washington'), (29, 'Carolina Panthers'), (30, 'Jacksonville Jaguars'), (31, 'AFC'), (32, 'NFC'), (33, 'Baltimore Ravens'), (34, 'Houston Texans')], primary_key=True, serialize=False)),
                ('city', models.CharField(choices=[('ATL', 'Atlanta'), ('BAL', 'Baltimore'), ('CHA', 'Charlotte'), ('CHI', 'Chicago'), ('CIN', 'Cincinnati'), ('CLE', 'Cleveland'), ('DEN', 'Denver'), ('DET', 'Detroit'), ('ER', 'East Rutherford'), ('FOX', 'Foxborough'), ('GLE', 'Glendale'), ('GB', 'Green Bay'), ('HOU', 'Houston'), ('IND', 'Indianapolis'), ('IRV', 'Irving'), ('JAX', 'Jacksonville'), ('KC', 'Kansas City'), ('LA', 'Los Angeles'), ('LAN', 'Landover'), ('MIA', 'Miami'), ('MIN', 'Minneapolis'), ('NAS', 'Nashville'), ('NO', 'New Orleans'), ('OAK', 'Oakland'), ('OP', 'Orchard Park'), ('ORL', 'Orlando'), ('PHI', 'Philadelphia'), ('PIT', 'Pittsburgh'), ('SF', 'San Francisco'), ('SEA', 'Seattle'), ('TAM', 'Tampa')], max_length=3)),
                ('stadium', models.CharField(choices=[('AS', 'Arrowhead Stadium'), ('ATS', 'AT&T Stadium'), ('BAS', 'Bank of America Stadium'), ('CLF', 'CenturyLink Field'), ('CWS', 'Camping World Stadium'), ('DHSP', 'Dignity Health Sports Park'), ('EF', 'Empower Field at Mile High'), ('FEF', 'FedExField'), ('FES', 'FirstEnergy Stadium'), ('FF', 'Ford Field'), ('GS', 'Gillette Stadium'), ('HF', 'Heinz Field'), ('HRS', 'Hard Rock Stadium'), ('LAMC', 'Los Angeles Memorial Coliseum'), ('LF', 'Lambeau Field'), ('LFF', 'Lincoln Financial Field'), ('LS', "Levi's Stadium"), ('LOS', 'Lucas Oil Stadium'), ('MBS', 'Mercedes-Benz Stadium'), ('MBD', 'Mercedes-Benz Superdome'), ('MLS', 'MetLife Stadium'), ('MTBS', 'M&T Bank Stadium'), ('NEF', 'New Era Field'), ('NRGS', 'NRG Stadium'), ('NS', 'Nissan Stadium'), ('PBS', 'Paul Brown Stadium'), ('RCC', 'RingCentral Coliseum'), ('RJS', 'Raymond James Stadium'), ('SF', 'Soldier Field'), ('SFS', 'State Farm Stadium'), ('TBF', 'TIAA Bank Field'), ('USBS', 'U.S. Bank Stadium')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('value', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('value', models.PositiveSmallIntegerField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.year')),
            ],
            options={
                'unique_together': {('year', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.SmallIntegerField(choices=[(0, 'Tbp'), (1, 'Home Team'), (2, 'Visitor Team'), (3, 'Tied Game')], default=0)),
                ('picked_tie_break', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='nfl.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_teams', to='nfl.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='visitor_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_teams', to='nfl.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='nfl.week'),
        ),
    ]
