# Generated by Django 3.0.3 on 2020-02-07 23:03

from django.db import migrations

from nfl.defines import CityChoices, TeamChoices, StadiumChoices


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TeamRev = apps.get_model('nfl', 'Team')
    TeamRev.objects.using(db_alias).bulk_create([
        TeamRev(
            city=CityChoices.CHICAGO,
            abbr=TeamChoices.BEARS,
            stadium=StadiumChoices.SF
        ),
        TeamRev(
            city=CityChoices.CINCINNATI,
            abbr=TeamChoices.BENGALS,
            stadium=StadiumChoices.PBS
        ),
        TeamRev(
            city=CityChoices.ORCHARD_PARK,
            abbr=TeamChoices.BILLS,
            stadium=StadiumChoices.NEF
        ),
        TeamRev(
            city=CityChoices.DENVER,
            abbr=TeamChoices.BRONCOS,
            stadium=StadiumChoices.EF
        ),
        TeamRev(
            city=CityChoices.CLEVELAND,
            abbr=TeamChoices.BROWNS,
            stadium=StadiumChoices.FES
        ),
        TeamRev(
            city=CityChoices.TAMPA,
            abbr=TeamChoices.BUCCANEERS,
            stadium=StadiumChoices.RJS
        ),
        TeamRev(
            city=CityChoices.GLENDALE,
            abbr=TeamChoices.CARDINALS,
            stadium=StadiumChoices.SFS
        ),
        TeamRev(
            city=CityChoices.LOS_ANGELES,
            abbr=TeamChoices.CHARGERS,
            stadium=StadiumChoices.DHSP
        ),
        TeamRev(
            city=CityChoices.KANSAS_CITY,
            abbr=TeamChoices.CHIEFS,
            stadium=StadiumChoices.AS
        ),
        TeamRev(
            city=CityChoices.INDIANAPOLIS,
            abbr=TeamChoices.COLTS,
            stadium=StadiumChoices.LOS
        ),
        TeamRev(
            city=CityChoices.IRVING,
            abbr=TeamChoices.COWBOYS,
            stadium=StadiumChoices.ATS
        ),
        TeamRev(
            city=CityChoices.MIAMI,
            abbr=TeamChoices.DOLPHINS,
            stadium=StadiumChoices.HRS
        ),
        TeamRev(
            city=CityChoices.PHILADELPHIA,
            abbr=TeamChoices.EAGLES,
            stadium=StadiumChoices.LFF
        ),
        TeamRev(
            city=CityChoices.ATLANTA,
            abbr=TeamChoices.FALCONS,
            stadium=StadiumChoices.MBS
        ),
        TeamRev(
            city=CityChoices.SAN_FRANCISCO,
            abbr=TeamChoices.FOURTYNINERS,
            stadium=StadiumChoices.LS
        ),
        TeamRev(
            city=CityChoices.EAST_RUTHERFORD,
            abbr=TeamChoices.GIANTS,
            stadium=StadiumChoices.MLS
        ),
        TeamRev(
            city=CityChoices.JACKSONVILLE,
            abbr=TeamChoices.JAGUARS,
            stadium=StadiumChoices.TBF
        ),
        TeamRev(
            city=CityChoices.EAST_RUTHERFORD,
            abbr=TeamChoices.JETS,
            stadium=StadiumChoices.MLS
        ),
        TeamRev(
            city=CityChoices.DETROIT,
            abbr=TeamChoices.LIONS,
            stadium=StadiumChoices.FF
        ),
        TeamRev(
            city=CityChoices.GREEN_BAY,
            abbr=TeamChoices.PACKERS,
            stadium=StadiumChoices.LF
        ),
        TeamRev(
            city=CityChoices.CHARLOTTE,
            abbr=TeamChoices.PANTHERS,
            stadium=StadiumChoices.BAS
        ),
        TeamRev(
            city=CityChoices.FOXBOROUGH,
            abbr=TeamChoices.PATRIOTS,
            stadium=StadiumChoices.GS
        ),
        TeamRev(
            city=CityChoices.OAKLAND,
            abbr=TeamChoices.RAIDERS,
            stadium=StadiumChoices.RCC
        ),
        TeamRev(
            city=CityChoices.LOS_ANGELES,
            abbr=TeamChoices.RAMS,
            stadium=StadiumChoices.LAMC
        ),
        TeamRev(
            city=CityChoices.BALTIMORE,
            abbr=TeamChoices.RAVENS,
            stadium=StadiumChoices.MTBS
        ),
        TeamRev(
            city=CityChoices.LANDOVER,
            abbr=TeamChoices.REDSKINS,
            stadium=StadiumChoices.FEF
        ),
        TeamRev(
            city=CityChoices.NEW_ORLEANS,
            abbr=TeamChoices.SAINTS,
            stadium=StadiumChoices.MBD
        ),
        TeamRev(
            city=CityChoices.SEATTLE,
            abbr=TeamChoices.SEAHAWKS,
            stadium=StadiumChoices.CLF
        ),
        TeamRev(
            city=CityChoices.PITTSBURGH,
            abbr=TeamChoices.STEELERS,
            stadium=StadiumChoices.HF
        ),
        TeamRev(
            city=CityChoices.HOUSTON,
            abbr=TeamChoices.TEXANS,
            stadium=StadiumChoices.NRGS
        ),
        TeamRev(
            city=CityChoices.NASHVILLE,
            abbr=TeamChoices.TITANS,
            stadium=StadiumChoices.NS
        ),
        TeamRev(
            city=CityChoices.MINNEAPOLIS,
            abbr=TeamChoices.VIKINGS,
            stadium=StadiumChoices.USBS
        ),
        TeamRev(
            city=CityChoices.ORLANDO,
            abbr=TeamChoices.AFC,
            stadium=StadiumChoices.CWS
        ),
        TeamRev(
            city=CityChoices.ORLANDO,
            abbr=TeamChoices.NFC,
            stadium=StadiumChoices.CWS
        ),
    ])


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TeamRev = apps.get_model('nfl', 'Team')
    TeamRev.objects.using(db_alias).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
