# Generated by Django 3.2.10 on 2022-01-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0002_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_teams', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='visitor_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_teams', to='nfl.team'),
        ),
    ]
